"""List every ambiguous name with the evidence needed to decide it.

The wiki has some names under several pages -- "Mysterious orb" is two quest
items, "Chest key" is six -- and the resolver refuses them on purpose. A guess
there is a wrong item id ringing the wrong thing in a player's bank.

Two ways of guessing were measured and both rejected:

* **Quest Helper's item requirements.** Neither the X Marks the Spot helper nor
  the Client of Kourend one names a mysterious orb at all, so this decides
  nothing for the case that prompted it.
* **Matching a page's parenthetical against the surrounding step text.** This
  resolved 7 of 60 names and most were wrong: "Adamant" became "Broken axe
  (adamant)", "Black" became "Dragon (race)", "Lunar" became "Stalagmites
  (Lunar Isle)". Confident and wrong is worse than absent.

So the decision stays with a person, and this report exists to make it quick:
each name, the pages it could mean, and the steps that use it in context.
Answers go in `curated/disambiguations.yaml`.

    python pipeline/disambiguation_report.py

Names that are genuinely vague -- "Adamant", "Bronze", "Black" are metals, not
items -- belong in `curated/item_collections.yaml` instead, and should be left
out of the disambiguation file entirely.
"""
import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def steps_using(name: str, guide: dict, limit: int = 4) -> list[str]:
    """The guide steps that mention this name, in document order."""
    found = []
    needle = name.lower()
    for section in guide["sections"]:
        for step in section.get("steps", []):
            if needle in step["text"].lower():
                found.append(f"[{section['title']}] {step['text']}")
                if len(found) >= limit:
                    return found
    return found


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--unresolved", type=Path,
                    default=REPO / "build" / "unresolved.json")
    ap.add_argument("--guide", type=Path, default=REPO / "dist" / "guide.json")
    ap.add_argument("--curated", type=Path,
                    default=REPO / "curated" / "disambiguations.yaml")
    ap.add_argument("--out", type=Path,
                    default=REPO / "docs" / "disambiguations.md")
    args = ap.parse_args()

    unresolved = json.loads(args.unresolved.read_text(encoding="utf-8"))
    guide = json.loads(args.guide.read_text(encoding="utf-8"))

    import yaml
    decided = set()
    if args.curated.exists():
        loaded = yaml.safe_load(args.curated.read_text(encoding="utf-8")) or {}
        decided = set((loaded.get("pages") or {}).keys())

    rows = {name: entry for name, entry in sorted(unresolved.items())
            if "disambiguation" in (entry.get("reason") or "")}

    lines = [
        "# Ambiguous names",
        "",
        "Generated by `pipeline/disambiguation_report.py`. Do not edit; put",
        "answers in `curated/disambiguations.yaml`.",
        "",
        f"{len(rows)} name(s) resolve to a wiki disambiguation page, of which",
        f"{len(decided & set(rows))} already have a curated answer.",
        "",
        "A name that is genuinely vague in the guide -- a metal, a tier, a kind",
        "of shop -- is not a disambiguation problem and belongs in",
        "`item_collections.yaml`. Leave those out.",
        "",
    ]

    for name, entry in rows.items():
        lines.append(f"## {name}" + ("  *(decided)*" if name in decided else ""))
        lines.append("")
        choices = entry.get("choices") or []
        if choices:
            lines.append("Could mean:")
            lines.extend(f"- `{c}`" for c in choices)
        else:
            lines.append("The page lists no candidates.")
        lines.append("")
        used = steps_using(name, guide)
        if used:
            lines.append("Used by:")
            lines.extend(f"- {u}" for u in used)
            lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"ambiguous names   {len(rows):5}")
    print(f"  already decided {len(decided & set(rows)):5}")
    print(f"  awaiting a call {len(rows) - len(decided & set(rows)):5}")
    print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
